config/routes.rb
Rails.application.routes.draw do
  get("/", { :controller => "places", :action => "index" })
  resources "entries"
  resources "places"
  resources "sessions"
  resources "users"

  get("/login", { :controller => "sessions", :action => "new" })
  get("/logout", { :controller => "sessions", :action => "destroy" })

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entry.rb
class Entry < ApplicationRecord
end

app/models/place.rb
class Place < ApplicationRecord
  has_one_attached :uploaded_image
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :current_user

  def current_user
    puts "------------------ code before every request ------------------"
    @current_user = User.find_by({ "id" => session["user_id"] })
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :require_login
  
  def new
    @user = User.find_by({ "id" => session["user_id"] })
  end

  def create
    @user = User.find_by({ "id" => session["user_id"] })
    
    if @user != nil
      @entry = Entry.new
      @entry["title"] = params["title"]
      @entry["description"] = params["description"]
      @entry["occurred_on"] = params["occurred_on"]
      @entry.uploaded_image.attach(params["uploaded_image"])
      @entry["place_id"] = params["place_id"]
      @entry.save
      redirect_to "/places/#{@entry["place_id"]}"
    else
      flash["notice"] = "Login first."
      redirect_to login_path
    end
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController

  def index
    @places = Place.all
  end

  def show
    @place = Place.find_by({ "id" => params["id"] })
    @entries = Entry.where({ "place_id" => @place["id"] })
  end

  def new
  end

  def create
    @place = Place.new
    @place["name"] = params["name"]
    @place.save
    redirect_to "/places"
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by({"email" => params["email"]})
    if @user != nil
    if BCrypt::Password.new(@user["password"]) == params["password"]
      session["user_id"] = @user["id"]
      flash["notice"] = "Welcome."
      redirect_to "/places"
    end
  else
      flash["notice"] = "Invalid email or password"
      redirect_to "/login"
  end
end

  def destroy
    session["user_id"] = nil
    flash["notice"] = "Goodbye."
    redirect_to "/login"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
    @user = User.new
    @user["username"] = params["username"]
    @user["email"] = params["email"]
    @user["password"] = BCrypt::Password.create(params["password"])
    @user.save
    flash[:notice] = "Thanks for signing up. Now login."
    redirect_to "/login"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/entries/new.html.erb
<h1>New Entry</h1>

<form action="/entries" method="post">
  <input type="hidden" name="place_id" value="<%= params["place_id"] %>">

  <p>
    <label for="title_input">Title</label>
    <input type="text" name="title" id="title_input">
  </p>

  <p>
    <label for="description_input">Description</label>
    <input type="text" name="description" id="description_input">
  </p>

  <p>
    <label for="occurred_on_input">Occurred On</label>
    <input type="date" name="occurred_on" id="occurred_on_input">
  </p>

  <button>Save</button>
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>Tacostagram Final</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="/stylesheets/application.css">
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <a class="navbar-brand" href="/">Action!</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="/">Home</a>
          </li>
        </ul>
        
        <ul class="navbar-nav mb-2 mb-lg-0">
          <% @user = User.find_by({ "id" => session["user_id"] }) %>
          <% if @user == nil %>
            <li class="nav-item"><a href="/users/new" class="nav-link">Sign Up</a></li>
            <li class="nav-item"><a href="/login" class="nav-link">Login</a></li>
          <% else %>
            <li class="nav-text">Logged in as: <%= @user["email"] %></li>
            <li class="nav-item"><a href="/logout" class="nav-link">Logout</a></li>
          <% end %>

          <li class="nav-item">
            <a href="/places/new/" class="btn btn-success">New Entry</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <div class="container mt-3">
    <% if flash["notice"] != nil %>
      <div class="alert alert-primary">
        <%= flash["notice"] %>
      </div>
    <% end %>

    <%= yield %>
  </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js" integrity="sha384-j1CDi7MgGQ12Z7Qab0qlWQ/Qqz24Gc6BM0thvEMVjHnfYGF0rmFCozFSxQBxwHKO" crossorigin="anonymous"></script>
  </body>
</html>

app/views/places/index.html.erb
<h1>Places</h1>

<ul>
  <% for place in @places %>
    <li><a href="/places/<%= place["id"] %>"><%= place["name"] %></a></li>
  <% end %>
</ul>

<p>
  <%= link_to "New Place", new_place_path, class: "btn btn-primary" %>
</p>

app/views/places/new.html.erb
<h1>New Place</h1>

<form action="/places" method="post" enctype="multipart/form-data">

<div class="mb-3">
  <label for="uploaded_image_input" class="form-label">Upload Image</label>
  <input type="file" name="uploaded_image" id="uploaded_image_input" class="form-control" accept="image/png, image/jpg, image/jpeg, image/gif">
</div>

  <p>
    <label for="name_input">Name</label>
    <input type="text" name="name" id="name_input">
  </p>

<button type="submit" class="btn btn-primary">Save</button>
</form>

app/views/places/show.html.erb
<h1 class="mb-4"><%= @place["name"] %></h1>

<% if @current_user %>
  <%= link_to "New Entry", new_entry_path(place_id: @place["id"]), class: "btn btn-primary mb-4" %>
<% end %>

<div class="row">
  <% @entries.each do |entry| %>
    <div class="col-md-4 mb-4">
      <div class="card h-100">
        <div class="card-body">
          <h5 class="card-title"><%= entry["title"] %></h5>
          <h6 class="card-subtitle mb-2 text-muted"><%= entry["occurred_on"] %></h6>
          <p class="card-text"><%= entry["description"] %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

<%= link_to "Back to All Places", places_path, class: "btn btn-secondary mt-3" %>

app/views/users/new.html.erb
<h1>New User Account</h1>

<form action="/users" method="post">
  <p>
    <label for="username">Username</label>
    <input type="text" name="username" id="username">
  </p>
  <p>
    <label for="email">Email</label>
    <input type="text" name="email" id="email">
  </p>
  <p>
    <label for="password">Password</label>
    <input type="text" name="password" id="password">
  </p>
    <button type="button" class="btn btn-primary">Signup</button>
  
</form>